# Generated by Django 5.2.4 on 2025-07-17 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_course_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='id',
        ),
        migrations.AlterField(
            model_name='exam',
            name='title',
            field=models.SlugField(primary_key=True, serialize=False),
        ),
    ]
