# Generated by Django 5.2.4 on 2025-07-17 22:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0004_remove_exam_id_alter_exam_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quetion_text', models.CharField(verbose_name=300)),
                ('marks', models.IntegerField()),
                ('exam', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='courses.exam')),
            ],
        ),
        migrations.CreateModel(
            name='ExamChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='questions.examquestion')),
            ],
        ),
    ]
