# Generated by Django 5.2.4 on 2025-07-17 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examquestion',
            name='quetion_text',
            field=models.CharField(max_length=200),
        ),
    ]
