# Generated by Django 5.2.4 on 2025-07-17 23:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_alter_examquestion_quetion_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examchoice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.examquestion'),
        ),
    ]
