# Generated by Django 5.2.4 on 2025-07-18 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_alter_examchoice_question'),
    ]

    operations = [
        migrations.RenameField(
            model_name='examquestion',
            old_name='quetion_text',
            new_name='question_text',
        ),
    ]
