# Generated by Django 5.2.4 on 2025-07-18 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_remove_exam_id_alter_exam_title'),
        ('questions', '0004_rename_quetion_text_examquestion_question_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examquestion',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.exam'),
        ),
    ]
